version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:44:94:68:e2:53:3e:6a:4f:51:f1:16:a5:e5:d3:24"
      - checkout
      - run: 
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
