version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:44:94:68:e2:53:3e:6a:4f:51:f1:16:a5:e5:d3:24"
      - checkout
      - restore_cache:
          keys:
            - dependences-york
      - run: 
          name: Install
          command: yarn install
      - save_cache:
          paths: 
            - node_modules
          key: dependences-york
      - run:
          name: Build
          command: yarn build
      - run:
          name: Shell Pre
          # chmod +x 赋予执行权限
          command: chmod +x scripts/deploy.sh
      - run:
          # 执行shell脚本
          name: Run deploy
          command: ./scripts/deploy.sh
